// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: auth/auth.proto

package authv1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on BasicAuth with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *BasicAuth) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BasicAuth with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in BasicAuthMultiError, or nil
// if none found.
func (m *BasicAuth) ValidateAll() error {
	return m.validate(true)
}

func (m *BasicAuth) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Username

	// no validation rules for Password

	if len(errors) > 0 {
		return BasicAuthMultiError(errors)
	}

	return nil
}

// BasicAuthMultiError is an error wrapping multiple validation errors returned
// by BasicAuth.ValidateAll() if the designated constraints aren't met.
type BasicAuthMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BasicAuthMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BasicAuthMultiError) AllErrors() []error { return m }

// BasicAuthValidationError is the validation error returned by
// BasicAuth.Validate if the designated constraints aren't met.
type BasicAuthValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BasicAuthValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BasicAuthValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BasicAuthValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BasicAuthValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BasicAuthValidationError) ErrorName() string { return "BasicAuthValidationError" }

// Error satisfies the builtin error interface
func (e BasicAuthValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBasicAuth.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BasicAuthValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BasicAuthValidationError{}

// Validate checks the field values on BearerAuth with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *BearerAuth) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BearerAuth with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in BearerAuthMultiError, or
// nil if none found.
func (m *BearerAuth) ValidateAll() error {
	return m.validate(true)
}

func (m *BearerAuth) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Token

	if len(errors) > 0 {
		return BearerAuthMultiError(errors)
	}

	return nil
}

// BearerAuthMultiError is an error wrapping multiple validation errors
// returned by BearerAuth.ValidateAll() if the designated constraints aren't met.
type BearerAuthMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BearerAuthMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BearerAuthMultiError) AllErrors() []error { return m }

// BearerAuthValidationError is the validation error returned by
// BearerAuth.Validate if the designated constraints aren't met.
type BearerAuthValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BearerAuthValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BearerAuthValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BearerAuthValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BearerAuthValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BearerAuthValidationError) ErrorName() string { return "BearerAuthValidationError" }

// Error satisfies the builtin error interface
func (e BearerAuthValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBearerAuth.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BearerAuthValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BearerAuthValidationError{}

// Validate checks the field values on AuthN with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AuthN) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuthN with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in AuthNMultiError, or nil if none found.
func (m *AuthN) ValidateAll() error {
	return m.validate(true)
}

func (m *AuthN) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Type

	switch v := m.Auth.(type) {
	case *AuthN_Basic:
		if v == nil {
			err := AuthNValidationError{
				field:  "Auth",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetBasic()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, AuthNValidationError{
						field:  "Basic",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, AuthNValidationError{
						field:  "Basic",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetBasic()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return AuthNValidationError{
					field:  "Basic",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	case *AuthN_Bearer:
		if v == nil {
			err := AuthNValidationError{
				field:  "Auth",
				reason: "oneof value cannot be a typed-nil",
			}
			if !all {
				return err
			}
			errors = append(errors, err)
		}

		if all {
			switch v := interface{}(m.GetBearer()).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, AuthNValidationError{
						field:  "Bearer",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, AuthNValidationError{
						field:  "Bearer",
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(m.GetBearer()).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return AuthNValidationError{
					field:  "Bearer",
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	default:
		_ = v // ensures v is used
	}

	if len(errors) > 0 {
		return AuthNMultiError(errors)
	}

	return nil
}

// AuthNMultiError is an error wrapping multiple validation errors returned by
// AuthN.ValidateAll() if the designated constraints aren't met.
type AuthNMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthNMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthNMultiError) AllErrors() []error { return m }

// AuthNValidationError is the validation error returned by AuthN.Validate if
// the designated constraints aren't met.
type AuthNValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthNValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthNValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthNValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthNValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthNValidationError) ErrorName() string { return "AuthNValidationError" }

// Error satisfies the builtin error interface
func (e AuthNValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthN.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthNValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthNValidationError{}

// Validate checks the field values on AuthZ with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *AuthZ) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on AuthZ with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in AuthZMultiError, or nil if none found.
func (m *AuthZ) ValidateAll() error {
	return m.validate(true)
}

func (m *AuthZ) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Root

	// no validation rules for Id

	// no validation rules for User

	// no validation rules for Username

	if all {
		switch v := interface{}(m.GetTimestamp()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, AuthZValidationError{
					field:  "Timestamp",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, AuthZValidationError{
					field:  "Timestamp",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetTimestamp()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return AuthZValidationError{
				field:  "Timestamp",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return AuthZMultiError(errors)
	}

	return nil
}

// AuthZMultiError is an error wrapping multiple validation errors returned by
// AuthZ.ValidateAll() if the designated constraints aren't met.
type AuthZMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m AuthZMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m AuthZMultiError) AllErrors() []error { return m }

// AuthZValidationError is the validation error returned by AuthZ.Validate if
// the designated constraints aren't met.
type AuthZValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e AuthZValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e AuthZValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e AuthZValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e AuthZValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e AuthZValidationError) ErrorName() string { return "AuthZValidationError" }

// Error satisfies the builtin error interface
func (e AuthZValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sAuthZ.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = AuthZValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = AuthZValidationError{}
